### ISSUE TITLE
K-9 Dog Ped For Jana

### ISSUE THREAD

**Issue by MsFxrgive** [ioShinigami/SoloRP-Directory#10]
name: K-9 
about: Better RP For Jana
title: 'K-9 Dog Ped Playable'
labels: enhancement
assignees: 'Mute Person'

Is your feature request related to a problem? Please describe.
Feature Request

Describe the feature you'd like
A K-9 Dog  i can have as model where i can interact with Peoples or Cars, Like sniff for drugs or if  you shoot your gun you got gunpowder in your clothes or smoke weed makes you smell after  weed and the dog can sniff that too. Would make rp better for me as i cant talk since im mute.

Additional context
https://www.lcpdfr.com/downloads/gta5mods/character/19996-german-shepherd-malinois-k9-dog/

**Comment by ioShinigami** [comment]
-Note that if doing this we found that theres an issue with the Models stamina , so a check for if is model we alter stamina values? or a more secure route of tabling the data to SQL , and storing identifiers with access have that buff while using such model.
