### ISSUE TITLE
Accessories/Possibly all clothing bug

### ISSUE THREAD

**Issue by costasoutos** [ioShinigami/SoloRP-Directory#11]
---
name: Accessories/Possibly all clothing bug
about: Issue with accessories and clothing unable to be put on after being taken off
title: 'Accessory/Clothing bug fix'
labels: bug
assignees: 'Devs'

---

**Describe the bug**
There is a bug where when you get your hat/glasses knocked off by a punch you are unable to put them back on with /g1 and /h1. There has also been the issue of taking your jacket off with /j0 and being unable to put it back on with /j1.

**To Reproduce**
Steps to reproduce the behaviour:
1. Equip an outfit containing a hat, glasses, and jacket
2. Get punched in the head
3. do /h1 and /g1
4. also do /j0 then /j1

**Expected Behaviour**
Hat, glasses, and jacket to be put back on after entering those commands

**Comment by ioShinigami** [comment]
```lua
 RegisterCommand('h1', function(source)
    Clothing.LoadAnimDict("mp_masks@standard_car@ds@")
    TaskPlayAnim(pedId, "mp_masks@standard_car@ds@", "put_on_mask", 4.0, 3.0, -1, 49, 1.0, 0, 0, 0 )
    Wait(600)

    --if Clothing.Data[0] then
        **SetPedPropIndex(pedId, 0, Clothing.Data[0]["Prop"], Clothing.Data[0]["Texture"], true)**
    --end
    ```
    Something to do with the Bold line , Leaving this for reference

**Comment by costasoutos** [comment]
Possible fix needs testing https://github.com/ioShinigami/Solo-RP2/commit/6db026a54b1aacad8b64e348a95fcfc6b6462e13

**Comment by ioShinigami** [comment]
Seems Glasses are still bugged
