### ISSUE TITLE
Mechanic Shop - Car Names

### ISSUE THREAD

**Issue by Teched321** [ioShinigami/SoloRP-Directory#110]
name: Feature Request
about: Suggest an idea for SoloRP
title: 'Mechanic Shop - Car Names'
labels: enhancement
assignees: ''

Is your feature request related to a problem? Please describe:
Currently when doing performance upgrades in the mechanic shop there has been some inconsistencies with the quotes due to the mechanics not knowing all of the car names/types/prices. This has led to customers being unhappy due to being quoted different prices when asking different mechanics about performance upgrades. 

Describe the feature you'd like:
I think it would be helpful to the mechanics if the car name could be displayed on screen when the performance menu is pulled up. I know in the base game the car name is displayed in the bottom right when you enter the vehicle, but it seems that has been removed in our city. 

Describe alternatives you've considered:
I have created a spreadsheet with performance prices attached for all vehicles. In the past we have tried getting the vehicle name from the customer, but that has led to some customers lying about the names in order to get a cheaper price or giving the incorrect name without realizing. 

Additional context
N/A

**Comment by ioShinigami** [comment]
I dont believe this is a needed system. As quotes on repairs/upgrades are normally just estimates that can be extremely wrong. I feel that this fits a line of Roleplay and human error. If there are inconsistencies at the Mechanic , I feel they should probably hire mechanics that are actually Car freaks who wont make those inconsistencies.
