### ISSUE TITLE
Disable Copyright music for Intro

### ISSUE THREAD

**Issue by iBrotato** [ioShinigami/SoloRP-Directory#111]
Hi there! 

_Apologies if there's a better format to place this in (feature request, etc.), but none seemed to fit._

I (and probably other content creators) am a bit concerned about the intro music that plays when flying into the city, as it could cause a DMCA strike to be placed against my account.  

Are we able to replace it with some copyright-free music?

Thanks,
iBrotato

**Comment by ioShinigami** [comment]
Your feature request does not meet the proper formatting. The proper template can be found here https://github.com/ioShinigami/SoloRP-Directory/issues/1
However this is already being taken care of and I will finish this week.
