### ISSUE TITLE
New Job!!

### ISSUE THREAD

**Issue by Jonjo447** [ioShinigami/SoloRP-Directory#113]
o basically i work for a big company called argos in the uk and they deliver items to customers houses everyday and in the truck all day theres 2 people a driver and a drivers mate and the driver will drive to the customers houses everyday and the drivers mate will get out and deliver these packages to the customers homes i thought this would be good for the server as it would force rp on people who have never met each other to eventually work together. think of it as a way for random people to connect with one another whilst doing waht they love, thaank you.

**Comment by ioShinigami** [comment]
Your feature request does not meet the proper formatting. The proper template can be found here

https://github.com/ioShinigami/SoloRP-Directory/issues/1
