### ISSUE TITLE
Indicator on top of character when someone speaks

### ISSUE THREAD

**Issue by mohamedaleya** [ioShinigami/SoloRP-Directory#116]
name: Feature Request
about: I saw this in another server and think it would be great to have especially when there's a crowd of people and you can't know who's talking. An indicator like a "?" on top of the player when he speaks would be of huge help I believe.
title: ''
labels: enhancement

**Comment by Jayysho** [comment]
Not a good idea

**Comment by Switty6** [comment]
I believe this would take out some of the immersive experience. You can watch their mouths, when someone is speaking their mouth is moving.
