### ISSUE TITLE
More locals 

### ISSUE THREAD

**Issue by Jayysho** [ioShinigami/SoloRP-Directory#117]
I think many people would agree that we would like to see more locals driving around and pedestrians walking more so the city doesn't look like a ghost town.

And for oxy runs randomize the selling cars so it's not just sultans everywhere in the streets or make something like at the end of every run you store the car.

**Comment by ioShinigami** [comment]
This was solved with commit : https://github.com/ioShinigami/Solo-RP2/commit/477504bce344949135950d77498251de2b08d48d
--
Also Your feature request does not meet the proper formatting. The proper template can be found here
https://github.com/ioShinigami/SoloRP-Directory/issues/1
