### ISSUE TITLE
Allow local cars to not instantly poof so they can be stashed/left for fun experiences/convenience.

### ISSUE THREAD

**Issue by patchell13** [ioShinigami/SoloRP-Directory#118]
I'm sure everyone has run into the situation where you do your job (garbage, deliveries etc) and you get back and your vehicle is gone. Also sure some people wish they could plant a car somewhere and drive to it later for some more fun/creative getaway ideas. Unfortunately the cars despawn if you get too far away from them.

I am aware there will be an impact on the server for every entity not immediately cleaned up by the server. This could be alleviated by the implementation of the Tow Job also listed/suggested on here (Maybe towing could be an additional place that you can get materials? Just a thought). Let anyone be able to request a tow on the radial menu. Having a 2x daily Tsunami that is scheduled, so that everyone is aware of the times, could also help with this and potentially other things in the city getting congested or bogged down.

**Comment by ioShinigami** [comment]
Your feature request does not meet the proper formatting. The proper template can be found here
https://github.com/ioShinigami/SoloRP-Directory/issues/1
