### ISSUE TITLE
Feature request: /lock command for vehicles & increased trigger range

### ISSUE THREAD

**Issue by mohamedaleya** [ioShinigami/SoloRP-Directory#119]
name: Feature Request
about: Currently you need to be at some kind of angle in order for your keys to trigger and unlock your car. Would it be possible to slightly increase this range? Also adding a /lock command would be great because sometimes L doesn't even work, or you keep spamming it and the vehicle unlocks and locks itself multiple times in a row.
title: /lock command for vehicles & increased trigger range
labels: enhancement

**Comment by Switty6** [comment]
This seems more like a bug. I'll take a look into it.

**Comment by Switty6** [comment]
This issue has been handled now.
