### ISSUE TITLE
Coffee Emote Bug

### ISSUE THREAD

**Issue by costasoutos** [ioShinigami/SoloRP-Directory#12]
---
name: Coffee Emote Bug
about: Coffee emote pulls out Lean instead
title: 'Coffee/Lean bug fix'
labels: bug
assignees: 'Devs'

---

**Describe the bug**
When doing the emote /coffee instead your character pulls out a styrofoam cup full of lean.

**To Reproduce**
Steps to reproduce the behaviour:
1. Type /e coffee
2. See lean

**Expected Behaviour**
For your character to drink a cup of coffee

**Screenshots**
https://i.imgur.com/Jlbii5C.png

**Additional context**
If this is intended as kind of a funny easter egg you can delete this, I just wasn't sure.

**Comment by ioShinigami** [comment]
Jordan troll
