### ISSUE TITLE
Need more boat spawns for fishing

### ISSUE THREAD

**Issue by bigdawg2997** [ioShinigami/SoloRP-Directory#127]
There are a bunch of opportunities to be had if more boats would be added to the city. One could go deep sea fishing, have a party on the yacht, go for a cruise, etc... I think boats can really only bring something beneficial to the city and cause no harm.

**Comment by ioShinigami** [comment]
Your feature request does not meet the proper formatting. The proper template can be found here https://github.com/ioShinigami/SoloRP-Directory/issues/1
