### ISSUE TITLE
Weed Bug

### ISSUE THREAD

**Issue by harrydoyle14** [ioShinigami/SoloRP-Directory#14]
name: Harry Doyle
about: it makes you run in the same spot.
title: '' Weed ESC Bug
labels: bug
assignees: ''

Describe the bug
When you go to weed press G and after a second press Escape. it will scuff you so you have to relog.

To Reproduce
Steps to reproduce the behaviour:

Go to Weed farm.
Press G
And also press ESC
See error
Expected Behaviour
It will make it so you cant move even if you no clip away.

**Comment by BubbleDK** [comment]
This has been fixed! Feel free to close it :)

433f97d2c4c08d85ff16b9677583817a725acd66

**Comment by ioShinigami** [comment]
We will push this fix tonight : April 7 2021 - an test it on the live server closing for now
