### ISSUE TITLE
Sitting in chairs

### ISSUE THREAD

**Issue by uglyshea** [ioShinigami/SoloRP-Directory#142]
Name : Connie Shwartz
About: The ability to sit in chairs

I have no idea if someone has already brought this up so sorry if I am just repeating it now but I would like an option to "3rd eye" a chair and have it automatically seat us into them. To clarify, by 3rd eye I mean press alt and have an option to sit pop up! Just like how you can do that with vending machines/ trays at burger shot and pizza place.

Reasoning: Currently sitting in chairs around the city is a very difficult task in terms of doing /sitchair and positioning it perfectly to where it actually appears that we are on the chair. As well as some chairs are too close to tables and it is not even possible to get close to looking normal while sitting. ADDITIONALLY 3rd eyeing chairs if its possible I would like for that to keep people seated while drinking/ eating.
This benefits everyone and especially places like the pizza place, taco shop, burger shot, anyone that RPs sitting down really.  

Thankyou for taking the time to read :3

**Comment by Switty6** [comment]
I'm on it 👍

**Comment by Switty6** [comment]
This has now been completed. Beta-testers shall be on it.
