### ISSUE TITLE
North Hospital

### ISSUE THREAD

**Issue by everydayimhustlin** [ioShinigami/SoloRP-Directory#152]
please add at least a circle to heal or revive people at the hospital to the north. I drove there thinking that it was open or something and its nothing it shouldnt even have a icon on the map if its not open or have some kinda working thing there

**Comment by Switty6** [comment]
We'll be working on the Hospitals to be handled by players. Currently there are not enough EMS employees available to open the Paleto one. This will be addressed on at a later date.
