### ISSUE TITLE
Recycling Center Enhancements

### ISSUE THREAD

**Issue by RonFondle** [ioShinigami/SoloRP-Directory#158]
Title: Recycle Center Enhancements
Labels: enhancement

**IS YOUR FETURE REQUEST RELATED TO A PROBLEM?**
Absolutely, with the increase in player base in the city. The Recycling center is struggling to keep up. With these changes, we believe the recycling center will run much smoother.

**DESCRIBE THE FEATURE THAT YOU WOULD LIKE:**
-Add Manager position, at an increased pay rate. ($100)
-Add Assistant Manager position, at an increased pay rate. ($80)
-Add locker only accessible by Boss, Manager, and Assistant Manager (NOT boss locker)
-Increase each locker weight to 8,000-10,000
-Add Boss Menu to back room for recycling purposes
-Remove the door lock from entrance. 24/7 service
-Add Vending Machine for food & drinks
-Add ATM or Invoice system (We do a lot of large transactions)
-Board to write on. ( employee of the week, prices etc...)
-Radio in warehouse for working employees
-Replace floor pallet with better system for buying and selling. (people struggle to use pallet... A lot...)

**ADDITIONAL TEXT:**
Please contact Ron Fondle or Weanydog on discord for more in depth descriptions.

**Comment by costasoutos** [comment]
https://github.com/ioShinigami/Solo-RP2/commit/277b1253aa9eaa8fcc2fe8beb06e4c37a75c380f

**Comment by Switty6** [comment]
This has been reworked and solved.
