### ISSUE TITLE
PDM fake safe removal

### ISSUE THREAD

**Issue by Jungle19D** [ioShinigami/SoloRP-Directory#161]
name: PDM fake safe removal
about: removal of fake safe
title: 'PDM fake safe removal'
labels: enhancement
assignees: ''

Is your feature request related to a problem? Please describe.
There is a fake safe presay in the office of PDM

Describe the feature you'd like
Can it please be removed

Describe alternatives you've considered
No real alternatives as there is already a boss menu in place with that area 

Additional context
![20210531132301_1](https://user-images.githubusercontent.com/81768787/120230406-d397af80-c214-11eb-816c-b63847aefe67.jpg)

**Comment by Switty6** [comment]
I will take a look on what's up with it as soon as I can.

**Comment by Mojito-Fivem** [comment]
This should be a qb-moneysafe config

**Comment by Mojito-Fivem** [comment]
I've removed this specific config but if a bossmenu system is being used I would just disable the whole qb-moneysafe resource
