### ISSUE TITLE
PDM Coffee Mechine

### ISSUE THREAD

**Issue by Jungle19D** [ioShinigami/SoloRP-Directory#162]
name: Feature Request
about: PDM
title: 'Coffee Mechine PDM'
labels: enhancement
assignees: ''

Is your feature request related to a problem? Please describe.
No

Describe the feature you'd like
Coffee Mechine - The ability to purchase coffee from it 

Describe alternatives you've considered
alternatively people can just goto the store and buy shit but it would make sense for it work as alot of people have asked for it 

Additional context
![20210531132326_1](https://user-images.githubusercontent.com/81768787/120231316-bd8aee80-c216-11eb-8d61-871d74e314a2.jpg)

**Comment by Switty6** [comment]
Interesting. Will be on my schedule.

**Comment by Mojito-Fivem** [comment]
@Switty6 You could add this to bt-target with `prop_vend_coffe_01`

**Comment by Switty6** [comment]
Yep. It's done now!
