### ISSUE TITLE
Bug Report:  Body Armor

### ISSUE THREAD

**Issue by ImageSR** [ioShinigami/SoloRP-Directory#166]
name: Bug Report
about: Create a report to help us improve SoloRP
title: ''
labels: bug
assignees: 'Devs'

---

**Describe the bug**
When applying Body Armor and you hit "ESC" to cancel the action and it uses the Body Armor.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Apply Body Armor
2. Hit "ESC" key 
3. Body Armor is removed from inventory.

**Expected Behaviour**
The action should be cancelled and you should not use the Body Armor.

**Additional context**
Also a known issue with Body Armor is that if you fly out after using Body Armor, and fly back in the Body Armor is no longer applied and you would need to use another Body Armor.  Currently Body Armor is very expensive and this seems like it should be addressed by lowering the cost of Body Armor or making the necessary fixes to make it worth using.

**Comment by uShifty** [comment]
Howdy @ImageSR I have taken a look into your report and pushed a fix to the developer branch, this issue will be resolved on the main build soon. We appreciate you taking time out of your day to make this report. Have a wonderful day!
