### ISSUE TITLE
employee list

### ISSUE THREAD

**Issue by MrBrainMonkey** [ioShinigami/SoloRP-Directory#19]
name: Rick
about: employee list i can't scroll through the list properly to see all the officers
assignees: 'Devs'

https://gyazo.com/c672ff1dbe1d96c462e7d7bcf4e85976

**Comment by ioShinigami** [comment]
Its not a pretty fix but youll be able to see the full employee list this way 
https://github.com/ioShinigami/Solo-RP2/commit/d42f5c6f38086bd11359b9c660891c16cc9d2161
