### ISSUE TITLE
Police 911 

### ISSUE THREAD

**Issue by Zolarov** [ioShinigami/SoloRP-Directory#21]
title: '911 calls as a police officer'
labels: bug
assignees: 'Devs'

---

**Describe the bug**
If you go on duty using the duty switch in the F1 menu, you will be unable to see any 911 calls show in the chat, but will see them in the MEOS app on the phone. If you go on duty using the Duty Switch in the station you will be able to see 911 calls show up in the chat box.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'F1 menu, Duty, Toggle Duty'
2. Do '/911, you will not see call show up'
3. And also do 'Go on duty using the switch in MRPD, you will see 911 calls'

**Expected Behaviour**
If you use F1 menu to toggle duty, it would be helpful to see 911 calls still incase you need to restart your game when away from the station and not have to respawn at the station just to see 911 calls

**Comment by BubbleDK** [comment]
8e86410d53aade45240e851384ffd41dea6e4c16

NEEDS TESTING

**Comment by ioShinigami** [comment]
We will merge this tonight and run some tests on live server with it

**Comment by ioShinigami** [comment]
Fix was not successful , However I believe jordan fixed this locally , so we can push the patch whenever he sends it to me.

**Comment by ioShinigami** [comment]
This was fixed , I Tested this myself and it seems to work fine.
Closing this unless it can be replicated again
