### ISSUE TITLE
Queue priority based on discord roles

### ISSUE THREAD

**Issue by Jordan581** [ioShinigami/SoloRP-Directory#32]
---
name: Feature Request
about: Queue System
title: Queue Priority based upon discord roles
labels: enhancement
assignees: 'Devs'

---

**Is your feature request related to a problem? Please describe.**
Relatively, the management of priority queue involves a lot of time consuming cross referencing and all has to be done manually. 

**Describe the feature you'd like**
When a player has a specified discord role then when they connect to the server they will be granted priority based on that role, (connectqueue).

**Describe alternatives you've considered**
Any system that could reduce the amount of manual cross referencing and entry of steam IDs to grant priority.

**Additional context**

[resources]/[qb]/qb-queue has a base for priority based on discord roles, however the queue system itself was not very stable from our previous experience. 

Template for priority levels (discord role Id's included):

bronze(816738137111134289) = 5

OG (812627512899141684) = 10 

gold (816738272117784606) = 15

Los Santos Police Department (783172230402015232)/Blaine County Sheriffs dpt (783172610690383883)/San Andreas Medial Team (783177309950705696)/lawyer (812203274551033907) = 20

diamond (816738393106022441)/judge (812203185820663808) = 25

content creator (812599664678797331)/excellent RP (826884003016605696) = 26

discord admin (783786243661627453) = 30

helper/trial mod (795049865435676683) = 35

developers (784135553889075240) = 95

staff (783080499446022204) = 99

owner (783080257661042728)/ Co-owner (797345997599932476) = 100

**Comment by ioShinigami** [comment]
This has been completed  ♡
