### ISSUE TITLE
Ammunation Quality of Life Changes

### ISSUE THREAD

**Issue by costasoutos** [ioShinigami/SoloRP-Directory#37]
---
name: Ammunation Quality of Life Changes
about: Adding a fine system for Ammunation as well as a tray to place weapons on when sale is made
title: 'Ammunation Quality of Life Changes'
labels: enhancement
assignees: 'Devs'

---

Is your feature request related to a problem? Please describe.
Currently Ammunation has to receive payment through a direct bank transfer or cash, both features not being the most secure. It would be best for both the business and the customers if the store could fine them the same way that Burgershot or other businesses do. Also currently weapons need to be handed off in a trunk or a glovebox, using a tray system would be more secure and immersive.

Describe the feature you'd like
The ability for Ammunation workers to use /fine to charge for weapons and have the funds go in to the society safe and also a tray on the desk to place the weapons in for a sale.

**Comment by costasoutos** [comment]
https://github.com/ioShinigami/Solo-RP2/commit/7cf163a68f5976b8b7f76390a13e8bec50092ff8

**Comment by costasoutos** [comment]
wow thanks for fixing this

**Comment by costasoutos** [comment]
You're welcome

**Comment by ioShinigami** [comment]
Holy shit taco I hate you
