### ISSUE TITLE
Server Password Security

### ISSUE THREAD

**Issue by BeeKez** [ioShinigami/SoloRP-Directory#48]
Just an idea, but i have noticed a lot of new people that seem to not have a clue about rules. Maybe a feature where when you first join the server there is a password you have to input that is hidden within the rules??

**Comment by ioShinigami** [comment]
Something we have already been planning on Thursday when we take the server down for downtime.

**Comment by ioShinigami** [comment]
As of patch 0.1.1 we have a queue system in the works that will prompt civs for a server password on join. This will work as a form of soft whitelisting.

**Comment by BeeKez** [comment]
Fantastic! Thanks for your hard work Shin! Hopefully something positive comes from this!
