### ISSUE TITLE
Vanilla Unicorn

### ISSUE THREAD

**Issue by TrezzKing** [ioShinigami/SoloRP-Directory#53]
So I am now the owner of the Vanilla Unicorn and I was wondering if it would be possible to create an entrance for the bartenders to serve drinks from behind the counter. Or if you guys could at least create a way to jump over the bar table to enter behind it and also to exit from it... On that same note would it be possible to create a storage space back there for drinks/food?

**Comment by costasoutos** [comment]
The bar should be enterable next restart but in terms of the storage space for now you'll have to continue using the boss stash, the drinks/food are bought from the store at the bar anyways so a storage isn't really needed

**Comment by ioShinigami** [comment]
As for patch 0.1.1 this section is now available,  as @costasoutos said , there are systems that you can now use so this shouldn't be an issue. I'll be closing this issue,  as the root of this issue has been fixed. If you want to open another one for stash if boss stash doesn't end up working out for you then feel free.
