### ISSUE TITLE
Renaming the Mechanic Shop

### ISSUE THREAD

**Issue by Teched321** [ioShinigami/SoloRP-Directory#56]
Name: Feature Request
About: Suggest an idea for SoloRP
Title: 'FTS Performance'
Labels: enhancement

### Is your feature request related to a problem? Please describe.
No.

### Describe the feature you'd like:
I recently took ownership of Stick It & Lick It mechanic shop. A lot of people including myself are not huge fans of the name. I would like to propose renaming the shop to FTS (For the Streets) Performance. I don't believe this change would require too much work, I would think it'd just be a refactor of the name. I would love to have this change in before the May 5th car show in the city, so that we can promote the new name. However, I understand if that's not a reasonable amount of time!

### Additional context:
Here is a logo I've created for the new shop name that would be used for future events that we sponsor.
![FTSPerformance](https://user-images.githubusercontent.com/82688519/115098357-4cf17200-9ef5-11eb-95e1-b61a755d6e07.png)

**Comment by ioShinigami** [comment]
Are you speaking about the map? As in the name on the map changed? Cause that can be done as far as the logo goes that isn't something really handled in code , a map guy will be able to change any visual type objects in the shop

**Comment by Teched321** [comment]
@ioShinigami Yes, just the name on the map and anywhere else it may appear in text. The logo can be ignored for now.

**Comment by costasoutos** [comment]
https://github.com/ioShinigami/Solo-RP2/commit/669c8b6ce3608be8f5e661bad62997b31e888d88
