### ISSUE TITLE
Lottery Ticket Balancing

### ISSUE THREAD

**Issue by UKmoz** [ioShinigami/SoloRP-Directory#59]
name: Lottery Ticket Balancing
about: Lottery tickets are not worth it at all after the nerf
title: ''
labels: lottery ticket, balancing
assignees: ''

**Describe the current reason for this balance request**
Lottery tickets were nerfed and the price was increased and the prize was reduced. This has resulted in the lottery tickets being unusable. I opened 50 tickets for $100 each, the maximum win I got on a ticket was $50. So the best ticket I opened had a 50% loss which makes them not even fun to play, and no chance to actually make money if you get lucky (the fun in gambling).

**Describe the solution you'd like**
Before when the lottery tickets paid too much, I opened quite a lot of tickets and averaged that in 300 tickets, you got triple your money back. Therefore, to make the odds in the house favour, I would suggest the previous rewards before it was nerfed, but just by increasing the prize of the card to $100 (as it is now). This would mean that unless you get lucky, you will eventually lose money in the long term. Though at that moment in time, the jackpot was not working correctly so additional balancing may be required.

**Comment by ioShinigami** [comment]
Lottery tickets were not intended to be a way of making money.  The idea was supposed to be for realism sake , the nerf per say was how the system should have came in the first place. The intention of the tickets were supposed to be more along a system of buy one a day and possibly get lucky. I can state from knowledge the max reward of the ticket is 1000$ but the rate of win was significantly reduced

**Comment by UKmoz** [comment]
> Lottery tickets were not intended to be a way of making money. The idea was supposed to be for realism sake , the nerf per say was how the system should have came in the first place. The intention of the tickets were supposed to be more along a system of buy one a day and possibly get lucky. I can state from knowledge the max reward of the ticket is 1000$ but the rate of win was significantly reduced

But for realism sake, the average lottery card has a 1/3-4 chance of a winning card, and while that could be just getting the money for the card back, it still has significantly higher chances than the current system as I opened 50 without making profit on a single ticket. I understand that they're not meant to be a way of making money but right now the odds are that bad it takes away the chance of even hoping for a win (which would only be a 10x win for a jackpot!), which in my opinion (in-game and real life) is where the fun is in gambling.
