### ISSUE TITLE
Vanilla Unicorn 

### ISSUE THREAD

**Issue by TrezzKing** [ioShinigami/SoloRP-Directory#62]
The V.U Does not have a boss menu. Not even Jason (the Discord community manager) can access it.
-Would it be possible to put Locks for the rear and side doors. This way people cant just get in the club without paying the entry fee?
(Also we need the tray back at the bar so we can serve drinks/food.)

**Comment by ioShinigami** [comment]
Should be fixed with commit: 
Closing this issue..
https://github.com/ioShinigami/Solo-RP2/commit/72434a64b39a2060de9d65a3f91cd1e34a99199f
