### ISSUE TITLE
Car cosmetics +

### ISSUE THREAD

**Issue by JakubBlack** [ioShinigami/SoloRP-Directory#63]
Window tints,
Neons,
stancing,
tire width, 
fake plates, 
custom plates, 

I'm sure these things are in mind for the city down the line.

**Comment by ioShinigami** [comment]
https://github.com/ioShinigami/SoloRP-Directory/issues/1
https://github.com/ioShinigami/SoloRP-Directory/issues/2
https://github.com/ioShinigami/SoloRP-Directory/issues/3

Please follow these templates when creating a suggestion, bug report , balance request. All requests not done in this manner will be ignored.
