### ISSUE TITLE
Buff Cab, Revert Changes

### ISSUE THREAD

**Issue by IGoddessI** [ioShinigami/SoloRP-Directory#64]
Cab before wasn't even worth doing, but the glitch made it fun and feasible in between low fairs. It takes so much time her money you actually make more money as a convicted criminal IN JAIL more money as an electrician than u do as a cab driver. 

Taxi cab takes the most player skill, and poses the greatest legal risk, tickets, speeding, jail time, evasion, etc.

The glitch made it fun and drove me to complete fairs faster and better just to get to the big payout one, i prefer one big fair, it made sense even rp sense a big tipper was sweet.

Timer per money its not even worth taking. But its even less fun now because .. did u change how it drives? cuz it feels suckier now and it takes more damage?

You have to nascar race plan your route and make pit stops and even drive first person and learn the cab to make good time and take racing lines.

**Comment by ioShinigami** [comment]
No changes were done to taxi job. You can follow along with any changes done to the server via the code-changelog or here when I respond to a report.
However we have no touched the taxi job.
