### ISSUE TITLE
Whitelist and/or application process to join SoloRP

### ISSUE THREAD

**Issue by ghost** [ioShinigami/SoloRP-Directory#76]
**Is your feature request related to a problem? Please describe.**
In short, I think there's a lot of low-effort RP going on, and plenty of folks that join for the sake of causing chaos or going full NVL.  A whitelist or application process would help ensure that the citizens of SoloRP have a solid idea in mind for their character, and would help reduce the amount of low-effort / NVL.

**Describe the feature you'd like**
An application process would consist of a short questionnaire, asking for some details about the character(s) that the potential Citizen wants to play.  A reviewer would then read through the answers and determine whether this potential citizen would be a "good fit" for the city.  If the citizen is "approved", they would be added to a whitelist and/or granted the "citizen" role in Discord, which would allow them to connect to the city.

**Describe alternatives you've considered**
One alternative might be a more open review process for when a new citizen is reported.  A _city council_ of active Citizens would review the report, decide whether the reported citizen should be _deported_.  

**Additional context**
Having an application process in place forces potential citizens to consider their character beyond just "I wanna rob banks and make money and ruin everyone's experience."  I think that this would work wonders to reduce the amount of disruptive, NVL experience that drives people out of the city.  

The _city council_ review process would also be viable, but I think this is a reactive response.  A proactive effort like a whitelist or application process might help cut down on the NVL RP before it happens, rather than after it's already ruined the experience. If it would help improve the RP experience for our city, I'd definitely be interested in helping with the whitelisting / application process, and/or the _city council_.

**Comment by Switty6** [comment]
Once the player base will be big enough, **maybe.**
