### ISSUE TITLE
Recycle Center Employee Tiers

### ISSUE THREAD

**Issue by clarkkent86** [ioShinigami/SoloRP-Directory#79]
Currently I have 2 other people as a boss because I'm not always around and they are there to basically be my "assistant managers" however it's only employee or boss and I can't fire a boss after I promote them. I'd like this to be changed somehow. Have a tier above employee that would have essentially the same rights as boss but I can still demote them or fire them if I need to.

**Comment by ioShinigami** [comment]
Invalid Format
